# frozen_string_literal: true

FactoryBot.define do
  factory :group do
    association :owner, factory: :user
    sequence(:name) { |n| "Group #{n}" }
    is_general_pool { false }
    # code is generated by the model on create.

    trait :general_pool do
      is_general_pool { true }
    end
  end
end
